#include <cctype>
#include <cstdlib>
#include <fstream>
#include <iostream>

#include <unistd.h>

#include "utils/rpcgen/generate.h"
#include "utils/rpcgen/parser.h"

using namespace oncrpc::rpcgen;
using namespace std;

[[noreturn]] void usage()
{
    cerr << "usage: rpcgen [-t] [-x] [-c] [-n namespace] file.x" << endl;
    exit(1);
}

static vector<string>
parseNamespaces(const string& namespaces)
{
    string ns = namespaces;
    vector<string> res;
    size_t i;
    while ((i = ns.find("::")) != string::npos) {
        res.push_back(ns.substr(0, i));
        ns = ns.substr(i + 2);
    }
    res.push_back(ns);
    for (const auto& s: res) {
        if (s.size() == 0 ||
            !(std::isalpha(s[0]) || s[0] == '_') ||
            !all_of(s.begin() + 1, s.end(),
                    [](char ch) {
                        return std::isalnum(ch) || ch == '_';
                    })) {
            cerr << "rpcgen: malformed namespace: " << namespaces << endl;
            exit(1);
        }
    }
    return res;
}

int
main(int argc, char* const argv[])
{
    bool generateTypes = false;
    bool generateXdr = false;
    bool generateClient = false;
    vector<string> namespaces;
    int opt;

    while ((opt = getopt(argc, argv, "txcn:")) != -1) {
        switch (opt) {
        case 't':
            generateTypes = true;
            break;

        case 'x':
            generateXdr = true;
            break;

        case 'c':
            generateClient = true;
            break;

        case 'n':
            namespaces = parseNamespaces(optarg);
            break;

        case '?':
        default:
            usage();
        }
    }
    argc -= optind;
    argv += optind;

    if (!(generateTypes || generateXdr || generateClient))
        usage();

    if (argc != 1)
        usage();
    ifstream file(argv[0]);
    ostream& str = cout;

    Parser parser(argv[0], file, str);
    try {
        auto spec = parser.parse();

        str << "// Please do not edit this file." << endl;
        str << "// It was generated using rpcgen." << endl;
        str << endl;
        str << "#include <array>" << endl;
        str << "#include <cstdint>" << endl;
        str << "#include <string>" << endl;
        str << "#include <vector>" << endl;
        str << "#include <rpc++/xdr.h>" << endl;
        if (generateClient)
            str << "#include <rpc++/client.h>" << endl;
        str << endl;
        
        for (const auto& ns: namespaces)
            str << "namespace " << ns << " {" << endl;

        str << endl;

        if (generateTypes) {
            GenerateTypes gen(str);
            spec->visit(&gen);
        }
        if (generateXdr) {
            GenerateXdr gen(str);
            spec->visit(&gen);
        }
        if (generateClient) {
            GenerateClient gen(str);
            spec->visit(&gen);
        }

        for (const auto& ns: namespaces)
            str << "} // " << ns << endl;
    }
    catch (runtime_error& e)
    {
        cerr << e.what() << endl;
        exit(1);
    }

    return 0;
}
